### ISSUE TITLE
Geo location upload API

### ISSUE THREAD

**Issue by shsjtu** [shsjtu/PennSHAPE#9]
Parameter: userID, attitude, longitude

**Comment by lize1985** [comment]
@shsjtu  fixed

curl  --header "Content-type: application/json" --request POST --data '{"geotime":"2015-10-31 12:00:01", "lat":"123.001", "lon":"111.11"}' http://localhost:9000/geolocation/1233321

**Comment by shsjtu** [comment]
Done
